# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-15 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('number', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('CRE', 'Creditor'), ('DEB', 'Debitor'), ('COS', 'Cost'), ('INC', 'Income')], default='CRE', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('number', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CostObject',
            fields=[
                ('number', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('document_number', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_transactions', to='accounting.Account')),
                ('contra_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contra_account_transactions', to='accounting.Account')),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.CostCenter')),
                ('cost_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.CostObject')),
            ],
        ),
    ]
