# Generated by Django 2.1.8 on 2019-04-26 16:27

import account.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180901_1555'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', account.models.CaseInsensitiveUserManager()),
            ],
        ),
    ]
