# Generated by Django 2.0.4 on 2018-07-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(choices=[('MR', 'Mr.'), ('MRS', 'Mrs.')], default='MR', max_length=3)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('street', models.CharField(blank=True, max_length=200, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('fax', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('membership_number', models.CharField(blank=True, max_length=100, null=True)),
                ('joined_at', models.DateField(blank=True, null=True)),
                ('terminated_at', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('CA', 'Cash'), ('RE', 'Remittance'), ('DE', 'Direct Debit')], default='DE', max_length=2)),
                ('iban', models.CharField(blank=True, max_length=34, null=True)),
                ('bic', models.CharField(blank=True, max_length=11, null=True)),
                ('debit_mandate_at', models.DateField(blank=True, null=True)),
                ('debit_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('field_1', models.CharField(blank=True, max_length=255, null=True)),
                ('field_2', models.CharField(blank=True, max_length=255, null=True)),
                ('field_3', models.CharField(blank=True, max_length=255, null=True)),
                ('field_4', models.CharField(blank=True, max_length=255, null=True)),
                ('field_5', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
