# Generated by Django 2.1.1 on 2018-09-02 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20180902_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='devision',
            new_name='division',
        ),
    ]
