# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20170825_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='field_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='field_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='field_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='field_4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='field_5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='salutation',
            field=models.CharField(choices=[('MR', 'Mr.'), ('MRS', 'Mrs.')], default='MR', max_length=3),
        ),
        migrations.AlterField(
            model_name='member',
            name='payment_method',
            field=models.CharField(choices=[('CA', 'Cash'), ('RE', 'Remittance'), ('DE', 'Direct Debit')], default='DE', max_length=2),
        ),
    ]
