# Generated by Django 2.1.1 on 2018-09-03 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20180903_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='payment_method',
            new_name='payment_frequency',
        ),
    ]
