# Generated by Django 2.1.1 on 2018-11-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20180903_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='payment_frequency',
            field=models.CharField(choices=[('MON', 'Monthly'), ('QUA', 'Quarterly'), ('HAL', 'Half-Yearly'), ('YEA', 'Yearly')], default='YEA', max_length=3),
        ),
    ]
