# Generated by Django 2.1.1 on 2018-12-19 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20181215_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'permissions': (('view_payment', 'Can view payment details'),)},
        ),
    ]
