# Generated by Django 2.1.5 on 2019-01-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20181219_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='subscription',
        ),
        migrations.AddField(
            model_name='member',
            name='subscription',
            field=models.ManyToManyField(blank=True, null=True, to='members.Subscription'),
        ),
    ]
