# Generated by Django 2.1.5 on 2019-01-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_auto_20190130_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='subscription',
            field=models.ManyToManyField(blank=True, to='members.Subscription'),
        ),
    ]
