# Generated by Django 2.1.5 on 2019-02-02 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_auto_20190202_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'permissions': (('view_field_salutation', 'Can view field salutation'), ('view_field_last_name', 'Can view field last_name'), ('view_field_first_name', 'Can view field first_name'), ('view_field_street', 'Can view field street'), ('view_field_zipcode', 'Can view field zipcode'), ('view_field_city', 'Can view field city'), ('view_field_birthday', 'Can view field birthday'), ('view_field_phone', 'Can view field phone'), ('view_field_mobile', 'Can view field mobile'), ('view_field_fax', 'Can view field fax'), ('view_field_email', 'Can view field email'), ('view_field_membership_number', 'Can view field membership number'), ('view_field_joined_at', 'Can view field joined at'), ('view_field_terminated_at', 'Can view field terminated at'), ('view_field_division', 'Can view field division'), ('view_field_payment_method', 'Can view field payment method'), ('view_field_iban', 'Can view field iban'), ('view_field_bic', 'Can view field bic'), ('view_field_debit_mandate_at', 'Can view field debit mandate at'), ('view_field_debit_reference', 'Can view field debit reference'), ('view_field_subscription', 'Can view field subscription'), ('view_field_field_1', 'Can view field field 1'), ('view_field_field_2', 'Can view field field 2'), ('view_field_field_3', 'Can view field field 3'), ('view_field_field_4', 'Can view field field 4'), ('view_field_field_5', 'Can view field field 5'), ('view_files', 'Can view files'))},
        ),
    ]
