# Generated by Django 2.1.5 on 2019-04-12 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_auto_20181206_1255'),
        ('members', '0015_auto_20190203_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='division',
            name='cost_center',
        ),
        migrations.RemoveField(
            model_name='division',
            name='cost_object',
        ),
        migrations.RemoveField(
            model_name='division',
            name='debitor_account',
        ),
        migrations.RemoveField(
            model_name='division',
            name='income_account',
        ),
        migrations.AddField(
            model_name='subscription',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.CostCenter'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='cost_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.CostObject'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='debitor_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.Account'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='income_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.Account'),
        ),
    ]
