# Generated by Django 2.1.5 on 2019-04-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_historicaldivision_historicalfile_historicalmember_historicalsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmember',
            name='subscriptions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='subscriptions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
