# Generated by Django 2.1.5 on 2019-04-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_auto_20190414_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmember',
            name='files',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='files',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
