# Generated by Django 2.1.8 on 2019-04-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_auto_20190414_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmember',
            name='division',
        ),
        migrations.AddField(
            model_name='historicalmember',
            name='divisions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='divisions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='member',
            name='division',
        ),
        migrations.AddField(
            model_name='member',
            name='division',
            field=models.ManyToManyField(blank=True, null=True, to='members.Division'),
        ),
    ]
