# Generated by Django 2.1.8 on 2019-04-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_auto_20190415_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='division',
            field=models.ManyToManyField(blank=True, to='members.Division'),
        ),
    ]
