# Generated by Django 2.1.1 on 2018-11-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TasksPermissionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('view_tasks', 'Can view tasks.'), ('run_tasks', 'Can run tasks')),
                'managed': False,
            },
        ),
    ]
