# Generated by Django 2.1.1 on 2018-12-14 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskspermissionmodel',
            options={'managed': False, 'permissions': (('run_tasks', 'Can run tasks'), ('run_subscription_task', 'Can run subscription task'), ('run_closure_task', 'Can run closure task'))},
        ),
    ]
