# Generated by Django 2.1.1 on 2018-12-14 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20181214_0206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskspermissionmodel',
            options={'managed': False, 'permissions': (('view_tasks', 'Can view tasks'), ('run_tasks', 'Can run tasks'), ('run_subscription_task', 'Can run subscription task'), ('run_closure_task', 'Can run closure task'), ('run_delete_terminated_members_task', 'Can run delete terminated members task'))},
        ),
    ]
