# Generated by Django 2.1.5 on 2019-02-02 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20181215_0032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskspermissionmodel',
            options={'managed': False, 'permissions': (('view_tasks', 'Can view tasks'), ('run_tasks', 'Can run tasks'), ('run_subscription_task', 'Can run subscription task'), ('run_closure_task', 'Can run closure task'), ('run_delete_terminated_members_task', 'Can run delete terminated members task'), ('run_delete_report_data_task', 'Can run delete report data task'))},
        ),
    ]
