BBBB BBBBBBBBBBBBB

XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    BB BBBBBBBBB
        BBBBBBBBBBBB BBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBB
    BBBB
        BBBBBBBBBBBB BBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB
    BBBBB
    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
        
    XXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXX