BB BBB BBBBBBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXX X XX XXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXX
                XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
    XXXXXX
    XXXXXX XXXXXXX
            
    XXXXXXXX
XXXXXX
BBBBB
XXXXXX XXXXXXX XXXXXXXBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX