# Generated by Django 2.1.1 on 2018-09-01 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': (('view_creditor', 'Can view creditor'), ('add_creditor', 'Can add creditor'), ('change_creditor', 'Can change creditor'), ('view_debitor', 'Can view debitor'), ('add_debitor', 'Can add debitor'), ('change_debitor', 'Can change debitor'), ('view_impersonal', 'Can view impersonal'), ('add_impersonal', 'Can add impersonal'), ('change_impersonal', 'Can change impersonal'))},
        ),
    ]
