# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-18 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20180318_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.CostCenter'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cost_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.CostObject'),
        ),
    ]
