# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-17 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20180317_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='contra_account',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.Account'),
        ),
    ]
