# Generated by Django 2.1.1 on 2018-11-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20180901_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='clearing_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
