# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-20 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20180318_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='document_number_generated',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
