# Generated by Django 2.1.1 on 2018-11-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_transaction_clearing_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='clearing',
            field=models.BooleanField(default=False),
        ),
    ]
