# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-20 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_transaction_document_number_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='document_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='document_number_generated',
            field=models.BooleanField(default=False),
        ),
    ]
