# Generated by Django 2.1.1 on 2018-11-08 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_account_clearing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='clearing',
        ),
    ]
