# Generated by Django 2.0.4 on 2018-07-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20180501_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='internal_number',
            field=models.IntegerField(default=0),
        ),
    ]
