# Generated by Django 2.1.1 on 2018-11-22 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0006_transaction_accounting_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosureTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('account_number', models.CharField(max_length=10)),
                ('account_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('document_number', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.CharField(max_length=255)),
                ('debit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('credit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cost_center_number', models.CharField(blank=True, max_length=10, null=True)),
                ('cost_center_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cost_center_description', models.TextField(blank=True, null=True)),
                ('cost_object_number', models.CharField(blank=True, max_length=10, null=True)),
                ('cost_object_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cost_object_description', models.TextField(blank=True, null=True)),
                ('document_number_generated', models.BooleanField(default=False)),
                ('internal_number', models.IntegerField(default=0)),
                ('reset', models.BooleanField(default=False)),
                ('clearing_number', models.IntegerField(blank=True, null=True)),
                ('accounting_year', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closuretransaction_create', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closuretransaction_update', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
