# Generated by Django 2.0.4 on 2018-07-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_transaction_internal_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reset',
            field=models.BooleanField(default=False),
        ),
    ]
