# Generated by Django 2.1.1 on 2018-12-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_closurebalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closurebalance',
            name='year',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
