# Generated by Django 2.1.8 on 2019-04-26 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0010_historicalaccount_historicalclosurebalance_historicalclosuretransaction_historicalcostcenter_histori'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalVirtualAccount',
            fields=[
                ('number', models.CharField(db_index=True, max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('initial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('active_from', models.DateField()),
                ('cost_center', models.CharField(max_length=255)),
                ('cost_objects', models.CharField(max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical virtual account',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='VirtualAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('initial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('active_from', models.DateField()),
                ('cost_center', models.CharField(max_length=255)),
                ('cost_objects', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virtualaccount_create', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virtualaccount_update', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
