# Generated by Django 2.1.8 on 2019-04-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_historicalvirtualaccount_virtualaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvirtualaccount',
            name='cost_center',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalvirtualaccount',
            name='cost_objects',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='virtualaccount',
            name='cost_center',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='virtualaccount',
            name='cost_objects',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
