# Generated by Django 2.1.1 on 2018-12-27 18:13

from django.db import migrations, models
import django.db.models.deletion
import reporting.models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_auto_20181227_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('resouce', models.FileField(upload_to=reporting.models.get_resource_path)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='report',
            name='report',
            field=models.FileField(upload_to='reports/definition'),
        ),
        migrations.AddField(
            model_name='resource',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.Report'),
        ),
    ]
