# Generated by Django 2.1.1 on 2018-12-27 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_auto_20181227_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='resouce',
            new_name='resource',
        ),
    ]
