# Generated by Django 2.1.1 on 2018-12-27 23:17

from django.db import migrations, models
import reporting.models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0005_auto_20181227_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='reports/definition'),
        ),
    ]
