# Generated by Django 2.1.1 on 2018-12-28 13:36

from django.db import migrations, models
import reporting.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0006_auto_20181228_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to=reporting.models.get_report_path),
        ),
    ]
