# Generated by Django 2.1.1 on 2018-12-28 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0007_auto_20181228_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'permissions': (('run_report', 'Can run report'),)},
        ),
    ]
