# Generated by Django 2.1.1 on 2018-12-29 14:07

from django.db import migrations
import separatedvaluesfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0008_auto_20181228_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='model',
            field=separatedvaluesfield.models.SeparatedValuesField(choices=[('MEM', 'Member'), ('DIV', 'Division'), ('SUB', 'Subscription'), ('ACC', 'Account'), ('COC', 'Costcenter'), ('COO', 'Costobject'), ('TRA', 'Transaction'), ('CTR', 'Closuretransaction'), ('CBA', 'Closurebalance')], default=['MEM'], max_length=255),
        ),
    ]
