# Generated by Django 2.1.1 on 2018-12-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0009_report_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='jsonql_query',
            field=models.TextField(default='members'),
            preserve_default=False,
        ),
    ]
